version: '3.9'

services:
    facerek-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/face-recognition-api
        ports: 
            - "3000:3000"
        environment:
            POSTGRES_URI: postgres://postgres:password@postgres:5432/face-recognition
            REDIS_URI: redis://redis:6379
            JWT_TOKEN: FSHJK4800HJSHOHSJKFSJKF
        links:
            - postgres
            - redis
    
    postgres:
        container_name: postgres
        build: ./postgres
        environment:
            POSTGRES_PASSWORD: password 
            POSTGRES_USER: postgres
            POSTGRES_DB: face-recognition
            POSTGRES_HOST: postgres
        ports:
            - "5432:5432"
    
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"